apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io/
    chart: longhorn
    targetRevision: v1.10.1
    helm:
      releaseName: longhorn
      values: |
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultReplicaCount: 3
        persistence:
          defaultClassReplicaCount: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
