apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.gitlab.io/
    chart: gitlab
    targetRevision: 9.7.0
    helm:
      releaseName: gitlab
      values: |
        global:
          edition: ce
          hosts:
            domain: xxpisal.online
            https: false
          ingress:
            configureCertmanager: false
            class: nginx
            tls:
              enabled: false
        certmanager:
          install: false
        nginx-ingress:
          enabled: false
        prometheus:
          install: false
        gitlab-runner:
          install: false
        postgresql:
          install: true
        redis:
          install: true
        gitaly:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
