apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.17.2
    helm:
      releaseName: harbor
      values: |
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: secret
            secret:
              secretName: harbor-xxpisal-online-tls
          ingress:
            hosts:
              core: harbor.xxpisal.online
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
        externalURL: https://harbor.xxpisal.online
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              storageClass: longhorn
            database:
              storageClass: longhorn
            redis:
              storageClass: longhorn
            trivy:
              storageClass: longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
