apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elastic-stack
    targetRevision: 8.19.6
    helm:
      releaseName: elk-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: elk-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
