apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      releaseName: minio
      values: |
        mode: standalone
        replicas: 1
        persistence:
          enabled: true
          size: 50Gi
          storageClass: longhorn
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: "1"
            memory: 4Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
